name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Regression Demowebshop
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/demowebshop/*.cy.js
          browser: chrome
